safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: /www/flipbit.co.uk
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:categories/:year/:month/:title.html

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []
